(function(){
  'use strict';const $=id=>document.getElementById(id),config=window.AC_PLATFORM_CONFIG||{};
  function message(text,type='error'){const box=$('message');box.textContent=text;box.className=`message show ${type}`}
  function destination(){const value=new URLSearchParams(location.search).get('next')||'';return value.startsWith('/')&&!value.startsWith('//')?value:''}
  function clearMessage(){$('message').className='message'}
  function esc(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
  document.querySelectorAll('.tab').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('.form').forEach(form=>form.classList.toggle('active',form.id===button.dataset.tab));clearMessage()}));
  $('signin').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;button.textContent='Signing in…';try{await ACAuth.signIn($('signInEmail').value.trim(),$('signInPassword').value);message('Signed in successfully.','good');await render();if(destination())location.href=destination()}catch(error){message(error.message)}finally{button.disabled=false;button.textContent='Sign In'}});
  $('signup').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;button.textContent='Creating account…';try{const data=await ACAuth.signUp($('signUpEmail').value.trim(),$('signUpPassword').value,$('companyName').value.trim());if(data.access_token){message('Your secure account is ready.','good');await render();if(destination())location.href=destination()}else message('Check your email to confirm the account, then sign in.','good')}catch(error){message(error.message)}finally{button.disabled=false;button.textContent='Create Secure Account'}});
  $('signOutBtn').addEventListener('click',async()=>{await ACAuth.signOut();message('Signed out.','good');render()});
  $('joinBtn').addEventListener('click',async()=>{const code=$('joinCode').value.trim();if(!code)return message('Enter the team code.');try{const headers={apikey:config.publishableKey,'Content-Type':'application/json',...(await ACAuth.headers())},response=await fetch(`${config.supabaseUrl}/rest/v1/rpc/join_organisation`,{method:'POST',headers,body:JSON.stringify({p_code:code})});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).message||'The team code could not be used.');await ACAuth.loadProfile();message('You joined the shared company workspace.','good');render()}catch(error){message(error.message)}});
  async function organisation(profile){if(!profile?.organisation_id)return null;try{const response=await fetch(`${config.supabaseUrl}/rest/v1/organisations?id=eq.${encodeURIComponent(profile.organisation_id)}&select=id,name,join_code`,{headers:{apikey:config.publishableKey,...(await ACAuth.headers())}});return response.ok?(await response.json())[0]||null:null}catch(_){return null}}
  async function renderTeam(profile){const host=$('teamMembers');host.innerHTML='';if(!profile?.organisation_id)return;try{const response=await fetch(`${config.supabaseUrl}/rest/v1/profiles?organisation_id=eq.${encodeURIComponent(profile.organisation_id)}&select=id,email,full_name,role&order=created_at`,{headers:{apikey:config.publishableKey,...(await ACAuth.headers())}});if(!response.ok)return;const rows=await response.json(),owner=profile.role==='owner';host.innerHTML=rows.map(row=>`<div class="member" data-user="${esc(row.id)}"><div><strong>${esc(row.full_name||row.email||'Team member')}</strong><span>${esc(row.email||'')}</span></div><select ${owner?'':'disabled'} aria-label="Team role"><option value="owner" ${row.role==='owner'?'selected':''}>Owner</option><option value="estimator" ${row.role==='estimator'?'selected':''}>Office / Estimator</option><option value="site_supervisor" ${row.role==='site_supervisor'?'selected':''}>Site Supervisor</option></select></div>`).join('');if(owner)host.querySelectorAll('select').forEach(select=>select.addEventListener('change',async()=>{select.disabled=true;try{const response=await fetch(`${config.supabaseUrl}/rest/v1/rpc/set_ac_member_role`,{method:'POST',headers:{apikey:config.publishableKey,'Content-Type':'application/json',...(await ACAuth.headers())},body:JSON.stringify({p_user:select.closest('.member').dataset.user,p_role:select.value})});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).message||'Role update failed.');message('Team role updated.','good')}catch(error){message(error.message);await renderTeam(profile)}finally{select.disabled=false}}))}catch(_){}}
  async function render(){await ACAuth.ready;const user=ACAuth.user(),profile=ACAuth.profile();$('guest').hidden=!!user;$('account').classList.toggle('show',!!user);if(!user)return;$('accountEmail').textContent=user.email||'';$('accountRole').textContent=profile?.role?profile.role.replace('_',' '):'Account created — database setup pending';const org=await organisation(profile);$('accountCompany').textContent=org?.name||user.user_metadata?.organisation_name||'Setup pending';$('cloudState').textContent=profile?.organisation_id?'Connected':'Run the included Supabase setup';if(profile?.role==='owner'&&org?.join_code){$('ownerCode').hidden=false;$('teamCode').textContent=org.join_code}else $('ownerCode').hidden=true;await renderTeam(profile)}
  render();
})();
