(function(){
  'use strict';
  const $=id=>document.getElementById(id),config=window.AC_PLATFORM_CONFIG||{};let membersById={};
  function message(text,type='error'){const box=$('message');box.textContent=text;box.className=`message show ${type}`;box.scrollIntoView({block:'nearest'})}
  function destination(){const value=new URLSearchParams(location.search).get('next')||'';return value.startsWith('/')&&!value.startsWith('//')?value:''}
  function clearMessage(){$('message').className='message'}
  function esc(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
  function apiHeaders(content=false){return ACAuth.headers().then(auth=>({apikey:config.publishableKey,...(content?{'Content-Type':'application/json'}:{}),...auth}))}
  async function rpc(name,body={}){const response=await fetch(`${config.supabaseUrl}/rest/v1/rpc/${name}`,{method:'POST',headers:await apiHeaders(true),body:JSON.stringify(body)}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||`${name} failed.`);return data}
  async function createPersonalWorkspace(name){await rpc('setup_ac_workspace',{p_name:String(name||'').trim()||'My Construction Workspace',p_team_code:''});await ACAuth.loadProfile()}

  document.querySelectorAll('.tab').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('.form').forEach(form=>form.classList.toggle('active',form.id===button.dataset.tab));clearMessage()}));
  $('signin').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;button.textContent='Signing in…';try{await ACAuth.signIn($('signInEmail').value.trim(),$('signInPassword').value);if(!ACAuth.hasAccess()&&!ACAuth.profile()){await createPersonalWorkspace(ACAuth.user()?.user_metadata?.organisation_name||'My Construction Workspace')}if(!ACAuth.hasAccess())throw new Error('Choose Continue Individually below, or enter a Team Code only if somebody invited you.');message('Signed in successfully.','good');await render();if(destination())location.href=destination()}catch(error){if(ACAuth.isSignedIn())await render();message(error.message)}finally{button.disabled=false;button.textContent='Sign In'}});
  $('signup').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter,teamCode=$('signUpTeamCode').value.trim();button.disabled=true;button.textContent=teamCode?'Joining team…':'Creating private workspace…';try{const data=await ACAuth.signUp($('signUpEmail').value.trim(),$('signUpPassword').value,$('companyName').value.trim(),teamCode);if(data.access_token){message(teamCode?'Your account joined the existing team.':'Your private Owner workspace is ready.','good');await render();if(destination())location.href=destination()}else message(`Check your email to verify the account, then sign in. ${teamCode?'Your team invitation will be applied automatically.':'Your private workspace will be ready—no Team Code is needed.'}`,'good')}catch(error){message(error.message)}finally{button.disabled=false;button.textContent='Create Secure Account'}});
  $('resetRequestBtn').addEventListener('click',async()=>{const email=$('signInEmail').value.trim();if(!email)return message('Enter your email in the Sign In form first.');try{await ACAuth.requestPasswordReset(email);message('Password reset email sent. Open its secure link on this device.','good')}catch(error){message(error.message)}});
  $('resendBtn').addEventListener('click',async()=>{const email=$('signUpEmail').value.trim();if(!email)return message('Enter the account email first.');try{await ACAuth.resendVerification(email);message('Verification email sent again.','good')}catch(error){message(error.message)}});
  $('passwordForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{await ACAuth.updatePassword($('newPassword').value);$('newPassword').value='';message('Password updated successfully.','good')}catch(error){message(error.message)}finally{button.disabled=false}});
  $('signOutBtn').addEventListener('click',async()=>{await ACAuth.signOut();message('Signed out.','good');render()});
  $('createPersonalBtn').addEventListener('click',async()=>{const button=$('createPersonalBtn');button.disabled=true;button.textContent='Creating workspace…';try{await createPersonalWorkspace($('personalWorkspaceName').value);message('Your individual workspace is active. Your Team Code is ready if you ever want to share it.','good');await render()}catch(error){message(error.message)}finally{button.disabled=false;button.textContent='Continue Individually'}});
  $('joinBtn').addEventListener('click',async()=>{const code=$('joinCode').value.trim();if(!code)return message('A Team Code is optional. Enter one only to join an existing team, or choose Continue Individually.');try{const profile=ACAuth.profile();if(!profile||profile.active===false)await rpc('setup_ac_workspace',{p_name:'',p_team_code:code});else await rpc('join_organisation',{p_code:code});await ACAuth.loadProfile();message('You joined the shared workspace as a Site Supervisor.','good');render()}catch(error){message(error.message)}});
  $('copyCodeBtn').addEventListener('click',async()=>{const code=$('teamCode').textContent.trim();if(!code)return;try{await navigator.clipboard.writeText(code);message('Team Code copied.','good')}catch(_){message(`Your Team Code is ${code}. Copy it and share it only with someone you trust.`,'good')}});
  $('rotateCodeBtn').addEventListener('click',async()=>{if(!confirm('Rotate the team code? The previous code will stop working immediately.'))return;try{const code=await rpc('rotate_ac_join_code');$('teamCode').textContent=String(code).replace(/^"|"$/g,'');message('Team code rotated. Share only the new code.','good');render()}catch(error){message(error.message)}});

  async function organisation(profile){if(!profile?.organisation_id)return null;try{const response=await fetch(`${config.supabaseUrl}/rest/v1/organisations?id=eq.${encodeURIComponent(profile.organisation_id)}&select=id,name,join_code,join_code_rotated_at`,{headers:await apiHeaders()});return response.ok?(await response.json())[0]||null:null}catch(_){return null}}
  async function changeRole(select,profile){select.disabled=true;try{await rpc('set_ac_member_role',{p_user:select.closest('.member').dataset.user,p_role:select.value});message('Team role updated and audited.','good');await renderTeam(profile);await renderActivity(profile)}catch(error){message(error.message);await renderTeam(profile)}finally{select.disabled=false}}
  async function changeAccess(button,profile){const row=button.closest('.member'),active=row.dataset.active==='true',verb=active?'revoke':'restore';if(active&&!confirm(`Revoke this team member? Their access will stop immediately and the shared team code will rotate.`))return;button.disabled=true;try{await rpc('set_ac_member_access',{p_user:row.dataset.user,p_active:!active});message(`Team access ${verb==='revoke'?'revoked; team code rotated':'restored'} and audited.`,'good');await ACAuth.loadProfile();await render()}catch(error){message(error.message)}finally{button.disabled=false}}
  async function renderTeam(profile){
    const host=$('teamMembers');host.innerHTML='';membersById={};if(!profile?.organisation_id||profile.active===false)return;
    try{const response=await fetch(`${config.supabaseUrl}/rest/v1/profiles?organisation_id=eq.${encodeURIComponent(profile.organisation_id)}&select=id,email,full_name,role,active,updated_at&order=created_at`,{headers:await apiHeaders()});if(!response.ok)throw new Error('Team list unavailable.');const rows=await response.json(),owner=profile.role==='owner';rows.forEach(row=>membersById[row.id]=row.full_name||row.email||'Team member');host.innerHTML=rows.map(row=>`<div class="member ${row.active===false?'inactive':''}" data-user="${esc(row.id)}" data-active="${row.active!==false}"><div><strong>${esc(row.full_name||row.email||'Team member')}</strong><span>${esc(row.email||'')} • ${row.active===false?'ACCESS REVOKED':'Active access'}</span></div><select ${owner&&row.active!==false?'':'disabled'} aria-label="Team role"><option value="owner" ${row.role==='owner'?'selected':''}>Owner</option><option value="estimator" ${row.role==='estimator'?'selected':''}>Office / Estimator</option><option value="site_supervisor" ${row.role==='site_supervisor'?'selected':''}>Site Supervisor</option></select><button type="button" class="${row.active===false?'':'danger'}" ${owner&&row.id!==ACAuth.user()?.id?'':'disabled'}>${row.active===false?'Restore':'Revoke'}</button></div>`).join('');if(owner){host.querySelectorAll('select:not([disabled])').forEach(select=>select.addEventListener('change',()=>changeRole(select,profile)));host.querySelectorAll('.member button:not([disabled])').forEach(button=>button.addEventListener('click',()=>changeAccess(button,profile)))}}
    catch(error){host.innerHTML=`<div class="activity-row"><strong>${esc(error.message)}</strong></div>`}
  }
  function describeAudit(row){const names={project_record_created:'Project record created',project_record_updated:'Project record updated',project_record_deleted:'Project record deleted',project_deleted:'Project deleted',ai_result_corrected:'AI result corrected by reviewer',workspace_created:'Project workspace created',workspace_synced:'Project workspace synced',member_joined:'Team member joined',member_role_changed:'Team role changed',member_access_revoked:'Team access revoked',member_access_restored:'Team access restored',team_code_rotated:'Team code rotated'};return names[row.action]||String(row.action||'Activity').replace(/_/g,' ')}
  async function renderActivity(profile){
    const host=$('activityList');if(!profile?.organisation_id||profile.active===false){host.innerHTML='<div class="activity-row"><strong>No active team access.</strong></div>';return}
    try{
      const headers=await apiHeaders(),base=`${config.supabaseUrl}/rest/v1`,org=encodeURIComponent(profile.organisation_id),[auditResponse,priceResponse]=await Promise.all([
        fetch(`${base}/ac_audit_log?organisation_id=eq.${org}&select=action,module,details,actor_id,created_at&order=created_at.desc&limit=20`,{headers}),
        fetch(`${base}/price_catalogue_history?organisation_id=eq.${org}&select=item_key,action,old_value,new_value,changed_by,created_at&order=created_at.desc&limit=20`,{headers})
      ]),audits=auditResponse.ok?await auditResponse.json():[],prices=priceResponse.ok?await priceResponse.json():[],rows=[...audits.map(row=>({...row,kind:'audit'})),...prices.map(row=>({...row,kind:'price'}))].sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).slice(0,18);
      host.innerHTML=rows.length?rows.map(row=>{const actor=membersById[row.actor_id||row.changed_by]||'Authorised user',title=row.kind==='price'?`Catalogue ${row.action}: ${row.item_key}`:describeAudit(row),detail=row.kind==='price'?(row.action==='update'?`${row.old_value?.builder_rate??'—'} → ${row.new_value?.builder_rate??'—'} ex GST`:'Versioned catalogue change'):(row.details?.title||row.module||'Team account');return `<div class="activity-row"><div><strong>${esc(title)}</strong><span>${esc(actor)} • ${esc(detail)}</span></div><time>${new Date(row.created_at).toLocaleString('en-AU')}</time></div>`}).join(''):'<div class="activity-row"><strong>No audited changes yet.</strong><span>Saved project records and catalogue edits will appear here.</span></div>';
    }catch(error){host.innerHTML=`<div class="activity-row"><strong>Activity unavailable</strong><span>${esc(error.message)}</span></div>`}
  }
  async function render(){
    await ACAuth.ready;const user=ACAuth.user(),profile=ACAuth.profile();$('guest').hidden=!!user;$('account').classList.toggle('show',!!user);if(!user)return;
    const active=!!profile?.organisation_id&&profile.active!==false;$('accountEmail').textContent=user.email||'';$('accountRole').textContent=active?(profile.role||'member').replace('_',' '):profile?.active===false?'Previous team inactive · individual setup available':'Individual setup available';$('accountRole').className=active?'':'status-bad';$('verificationState').textContent=user.email_confirmed_at?'Verified':'Pending verification';$('verificationState').className=user.email_confirmed_at?'status-good':'status-bad';
    const org=await organisation(profile);$('accountCompany').textContent=active?(org?.name||user.user_metadata?.organisation_name||'Workspace'):'Choose individual or team';$('cloudState').textContent=active?'Connected with RLS':'Ready to create individual workspace';$('catalogueState').textContent=active?'Checked by server on open':'Available after workspace setup';$('teamArea').hidden=false;$('personalChoice').hidden=active;$('joinChoice').hidden=active;
    const owner=active&&profile.role==='owner';if(owner&&org?.join_code){$('ownerCode').hidden=false;$('teamCode').textContent=org.join_code;$('codeAge').textContent=org.join_code_rotated_at?`Rotated ${new Date(org.join_code_rotated_at).toLocaleString('en-AU')}`:''}else $('ownerCode').hidden=true;
    await renderTeam(profile);await renderActivity(profile);
  }
  const redirectType=sessionStorage.getItem('ac_auth_redirect_type');if(redirectType){sessionStorage.removeItem('ac_auth_redirect_type');setTimeout(()=>message(redirectType==='recovery'?'Secure recovery link accepted. Enter a new password below.':'Secure email link accepted.','good'),0)}
  render();
})();
