(function(){
  'use strict';
  const $=id=>document.getElementById(id),DRAFT_KEY='ac_permit_checklist_draft_v1',RESTORE_KEY='ac_project_permit_restore_v1';
  const IDS=['projectName','projectType','address','council','deliveryRole','projectValue','followUpDate','notes'];
  const CHECKS=['structural','external','demolition','plumbing','electrical','poolSpa','boundary','excavation','easement','roadAsset','treeRemoval','asbestos','heritage','bushfire','flood','unknownControls'];
  const TYPE_LABEL={
    'internal-renovation':'Internal renovation','structural-alteration':'Structural alteration','extension':'House extension / addition','new-home':'New house / townhouse / unit','deck-verandah':'Deck, verandah or pergola','shed-garage':'Shed, garage or carport','pool-spa':'Swimming pool or spa','demolition':'Demolition','fence-retaining':'Fence or retaining wall','change-use':'Change of use / subdivision',other:'Other building or property work'
  };
  const URLS={
    planning:'https://www.planning.vic.gov.au/planning-approvals/planning-enquiries-and-requests/applying-for-a-planning-permit',
    property:'https://www.planning.vic.gov.au/planning-schemes/planning-property-report',
    building:'https://www.building.vic.gov.au/before-you-start-building/agreements-and-contracts',
    surveyor:'https://www.building.vic.gov.au/before-you-start-building/building-standards-in-victoria',
    owner:'https://www.bpc.vic.gov.au/owner-builders/becoming-an-owner-builder/eligibility',
    warranty:'https://www.bpc.vic.gov.au/home-owners/insurance-for-domestic-building-work/domestic-building-insurance-and-home-warranty',
    electrical:'https://www.energysafe.vic.gov.au/certificates-electrical-safety/certificates-electrical-safety-consumers',
    asbestos:'https://www.worksafe.vic.gov.au/understand-and-manage-asbestos-workplaces',
    bushfire:'https://www.planning.vic.gov.au/guides-and-resources/guides/all-guides/building-in-the-bushfire-management-overlay'
  };
  let lastResult=null,recordRef=null;

  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
  function readState(){const state={};IDS.forEach(id=>state[id]=$(id).value);CHECKS.forEach(id=>state[id]=$(id).checked);state.documents={};document.querySelectorAll('[data-doc]').forEach(row=>{state.documents[row.dataset.doc]={done:row.querySelector('input[type=checkbox]').checked,note:row.querySelector('input[type=text]').value}});return state}
  function writeState(state={}){IDS.forEach(id=>{if(state[id]!==undefined)$(id).value=state[id]});CHECKS.forEach(id=>$(id).checked=!!state[id])}
  function add(list,id,name,status,authority,why,next,source){if(list.some(item=>item.id===id)){const existing=list.find(item=>item.id===id);if(status==='likely')existing.status='likely';if(why&&!existing.why.includes(why))existing.why+=' '+why;return}list.push({id,name,status,authority,why,next,source})}
  function assess(input){
    const s=input||readState();if(!s.projectType)throw new Error('Choose a project type before generating the checklist.');
    const permits=[],externalTypes=['extension','new-home','deck-verandah','shed-garage','pool-spa','demolition','fence-retaining','change-use'],buildingTypes=['structural-alteration','extension','new-home','deck-verandah','shed-garage','pool-spa','demolition','fence-retaining'];
    const planningLikely=['extension','new-home','change-use'].includes(s.projectType)||s.heritage||s.bushfire||s.flood;
    add(permits,'planning','Planning permit',planningLikely?'likely':'check','Local council planning department',planningLikely?'The project type or a declared overlay commonly triggers planning assessment.':'Planning and building permits are separate. Zoning, overlays, neighbourhood character, title restrictions and exact dimensions can still trigger a planning permit.','Get a Planning Property Report, then ask council to confirm whether a planning permit is required.',URLS.planning);
    const buildingLikely=buildingTypes.includes(s.projectType)||s.structural||s.external||s.demolition||s.poolSpa||s.excavation;
    add(permits,'building','Building permit',buildingLikely?'likely':'check','Appointed registered building surveyor',buildingLikely?'Structural, external, demolition, pool/spa and many structure types generally require a building-permit decision.':'Some non-structural internal renovations may be exempt, but only a competent authority should confirm the exemption for the full scope.','Give the scope and plans to a registered building surveyor before work starts.',URLS.building);
    if(s.boundary||s.excavation||['extension','new-home','fence-retaining'].includes(s.projectType))add(permits,'report-consent','Report and consent / siting approval','check','Local council and appointed building surveyor','Boundary setbacks, height, overlooking, access, siting variations or adjoining land may require council report and consent.','Ask the surveyor to identify each siting regulation and whether council consent is needed.',URLS.surveyor);
    if(s.boundary||s.excavation||s.demolition)add(permits,'protection','Protection work process','check','Appointed building surveyor / adjoining owner','Work that may affect an adjoining property can trigger formal protection-work notices, insurance and documentation.','Do not enter neighbouring land or start affecting work until the surveyor confirms the protection-work process.',URLS.surveyor);
    if(s.deliveryRole==='owner-builder')add(permits,'owner-builder','Owner-builder Certificate of Consent',s.projectValue==='over20'?'likely':'check','Building and Plumbing Commission (BPC)',s.projectValue==='over20'?'The entered project value is above the current $20,000 Certificate of Consent threshold.':'Current eligibility, value thresholds and exemptions must be confirmed before applying for a building permit.','Check current BPC eligibility and obtain the certificate if required.',URLS.owner);
    if(s.deliveryRole==='registered-builder'||s.projectValue==='over20')add(permits,'warranty','Home Warranty / domestic building insurance evidence','check','Registered builder, insurer and BPC','Eligible domestic building work may require current Home Warranty or domestic building insurance evidence, depending on the contract date, value and work.','Have the builder and building surveyor confirm the current insurance evidence before contract and permit steps.',URLS.warranty);
    if(s.plumbing||['internal-renovation','extension','new-home','pool-spa'].includes(s.projectType))add(permits,'plumbing','Plumbing approvals and compliance certificate','check','Licensed plumber, BPC and relevant water authority','Plumbing, drainage, gas and some water-authority work must be performed and certified under the applicable plumbing requirements.','Ask the licensed plumber to identify permit, booking, inspection and compliance-certificate requirements.',URLS.building);
    if(s.electrical||['internal-renovation','extension','new-home','pool-spa'].includes(s.projectType))add(permits,'electrical','Certificate of Electrical Safety','check','Licensed electrician / Energy Safe Victoria','Electrical installation work requires a Certificate of Electrical Safety and must be carried out by appropriately licensed workers.','Confirm whether the work is prescribed or non-prescribed and retain the certificate.',URLS.electrical);
    if(s.poolSpa||s.projectType==='pool-spa')add(permits,'pool','Pool/spa building permit, barrier and council registration','likely','Registered building surveyor and local council','Victorian pool/spa construction and safety barriers have building-permit, inspection and registration obligations.','Confirm the barrier design, permit, inspection schedule and council registration before use.',URLS.building);
    if(s.demolition||s.projectType==='demolition')add(permits,'demolition','Demolition permit and service-disconnection controls','likely','Registered building surveyor, utilities and council','Demolition generally requires a building-permit decision and safe disconnection, site protection and waste controls.','Confirm demolition practitioner, utility disconnections, protection work and council asset controls.',URLS.building);
    if(s.asbestos||s.demolition||s.projectType==='demolition')add(permits,'asbestos','Asbestos assessment, licensed removal and notification','check','WorkSafe Victoria and a competent/licensed asbestos professional','Suspected asbestos changes the safe-removal, licensing, notification, air-monitoring and disposal path.','Stop disturbing suspected material and obtain a competent asbestos assessment before demolition or renovation.',URLS.asbestos);
    if(s.roadAsset)add(permits,'asset','Asset protection / road occupation / vehicle crossing permit','check','Local council','Skips, cranes, hoardings, footpath occupation, crossovers and work near council assets are commonly controlled by local permits.','Ask council which local-law and asset-protection permits, bonds and inspections apply.',URLS.property);
    if(s.treeRemoval)add(permits,'tree','Tree or vegetation removal approval','check','Local council planning/local-laws team','Planning overlays and local laws can restrict pruning or removal, including on private land.','Identify the species, trunk size and overlay/local-law controls before pruning or removal.',URLS.property);
    if(s.easement)add(permits,'easement','Build-over-easement / sewer or drainage consent','check','Relevant water authority and local council','Building or excavation near an easement, sewer, drain or authority asset can require separate consent and engineering.','Obtain title/service information and written authority consent before finalising design.',URLS.property);
    if(s.heritage)add(permits,'heritage','Heritage planning approval','likely','Local council and, where applicable, Heritage Victoria','The user identified a heritage control. External works and some other changes can require approval.','Confirm the exact heritage controls and endorsed scope before design is finalised.',URLS.planning);
    if(s.bushfire)add(permits,'bushfire','Bushfire planning and construction assessment','likely','Local council, building surveyor and qualified bushfire practitioner','The Bushfire Management Overlay can trigger a planning permit and bushfire design evidence for some development.','Confirm the BMO path, BAL evidence, defendable space and referral requirements.',URLS.bushfire);
    if(s.flood)add(permits,'flood','Flood / inundation referral and design approval','check','Local council and relevant referral authority','Flood or inundation controls can change floor levels, siting, access, drainage and referral requirements.','Obtain current authority information and written design requirements.',URLS.property);
    if(s.unknownControls)add(permits,'property-report','Planning Property Report and title check','likely','VicPlan, Land Use Victoria and local council','Zoning and overlays have not been checked, so the permit screen is missing essential property-specific controls.','Download the free Planning Property Report and obtain a current title/plan before relying on this checklist.',URLS.property);

    const docs=[
      {name:'Property and scope',items:[['planning-report','Planning Property Report / VicPlan zoning and overlays'],['title','Current title, plan of subdivision, covenants and easements'],['scope','Written scope, dimensions and estimated project value'],['photos','Current site and building photographs'],['council-advice','Written council advice / pre-application notes']]},
      {name:'Design and building',items:[['site-survey','Feature and level survey / site plan'],['drawings','Existing and proposed floor plans, elevations and sections'],['specifications','Specifications, materials and finishes schedule'],['engineering','Structural engineering drawings and computations'],['soil','Soil report / footing information where relevant'],['energy','Energy-efficiency report where relevant'],['surveyor','Building surveyor appointment and permit application'],['planning-permit','Planning permit and endorsed plans, if required']]},
      {name:'People, contracts and insurance',items:[['practitioners','Practitioner names, registration/licence numbers and responsibilities'],['contract','Domestic building contract / quotation and scope exclusions'],['owner-consent','Owner-builder Certificate of Consent, if required'],['warranty','Current Home Warranty / insurance evidence, if required'],['protection','Protection-work notices, adjoining-owner response and insurance, if required']]},
      {name:'Trade and completion records',items:[['plumbing-docs','Plumbing permits/bookings, approved plans and compliance certificate'],['electrical-docs','Certificate of Electrical Safety'],['water-consent','Water-authority / build-over-easement consent'],['inspections','Mandatory inspection records and occupancy permit / certificate of final inspection'],['as-built','As-built drawings, warranties and operating manuals']]}
    ];
    if(s.heritage||s.bushfire||s.flood||s.treeRemoval)docs.push({name:'Specialist planning evidence',items:[['planning-report-detail','Planning report and response to zoning/overlays'],['heritage-report','Heritage impact statement, if required'],['bushfire-report','Bushfire/BAL assessment and management statement, if required'],['flood-report','Flood level / authority referral response, if required'],['arborist','Arborist report and tree-protection plan, if required']]});
    if(s.demolition||s.asbestos||s.projectType==='demolition')docs.push({name:'Demolition and hazardous materials',items:[['demo-plan','Demolition methodology and site-safety plan'],['services','Utility disconnection confirmations'],['asbestos-survey','Asbestos survey / register and removal scope'],['removalist','Removalist licence, notifications, clearance and disposal records'],['waste','Waste and recycling plan']]});
    if(s.poolSpa||s.projectType==='pool-spa')docs.push({name:'Pool and spa',items:[['pool-plans','Pool/spa and safety-barrier plans'],['pool-permit','Building permit and mandatory inspection records'],['pool-registration','Council registration and barrier compliance evidence']]});
    if(s.roadAsset)docs.push({name:'Council assets and access',items:[['asset-permit','Asset-protection / road-occupation permit and bond'],['traffic','Traffic/pedestrian management and delivery plan'],['crossover','Vehicle crossing / crossover approval']]});
    return{permits,docs,generatedAt:new Date().toISOString(),typeLabel:TYPE_LABEL[s.projectType]||'Project',version:'Official-source rules last reviewed 15 July 2026'};
  }
  function render(result,state={}){
    lastResult=result;const docsState=state.documents||{};$('resultTitle').textContent=(state.projectName||result.typeLabel)+' — preliminary screen';$('resultMeta').textContent=[result.typeLabel,state.address,state.council,result.version].filter(Boolean).join(' • ');
    $('permitList').innerHTML=result.permits.map(item=>`<article class="permit ${item.status}"><div class="permit-top"><h3>${esc(item.name)}</h3><span class="status">${item.status==='likely'?'Likely required':'Confirm with authority'}</span></div><p>${esc(item.why)}</p><p class="authority">Responsible check: ${esc(item.authority)}</p><p><strong>Next:</strong> ${esc(item.next)} <a href="${esc(item.source)}" target="_blank" rel="noopener">Official guidance ↗</a></p></article>`).join('');
    $('docGroups').innerHTML=result.docs.map(group=>`<section class="doc-group"><h3>${esc(group.name)}</h3>${group.items.map(([id,label])=>{const saved=docsState[id]||{};return`<div class="doc-item" data-doc="${esc(id)}"><input id="doc-${esc(id)}" type="checkbox" ${saved.done?'checked':''}><label for="doc-${esc(id)}">${esc(label)}</label><input type="text" value="${esc(saved.note||'')}" placeholder="Reference, status or note"></div>`}).join('')}</section>`).join('');
    const likely=result.permits.filter(item=>item.status==='likely').length;$('likelyCount').textContent=String(likely);$('checkCount').textContent=String(result.permits.length-likely);$('docCount').textContent=String(result.docs.reduce((sum,group)=>sum+group.items.length,0));$('results').classList.add('show');document.body.classList.add('result-ready');
  }
  function saveDraft(){const state=readState();localStorage.setItem(DRAFT_KEY,JSON.stringify({state,result:lastResult,savedAt:new Date().toISOString()}));toast('Permit checklist draft saved on this device.')}
  function toast(message){const node=document.createElement('div');node.className='acp-toast';node.textContent=message;document.body.appendChild(node);setTimeout(()=>node.remove(),2800)}
  function reset(){if(!confirm('Reset this Permit Checklist? This clears the unsaved form and generated checklist.'))return;IDS.forEach(id=>$(id).value=id==='deliveryRole'||id==='projectValue'?'unknown':'');CHECKS.forEach(id=>$(id).checked=false);localStorage.removeItem(DRAFT_KEY);lastResult=null;recordRef=null;$('results').classList.remove('show');document.body.classList.remove('result-ready');$('restoreNote').classList.remove('show')}
  $('generate').addEventListener('click',()=>{try{const state=readState(),result=assess(state);render(result,state);saveDraft();window.ACAnalytics?.track?.('estimate_completed','permit-checklist');$('results').scrollIntoView({behavior:'smooth',block:'start'})}catch(error){alert(error.message)}});
  $('saveDraft').addEventListener('click',saveDraft);$('reset').addEventListener('click',reset);$('print').addEventListener('click',()=>print());
  window.ACProjectCapture=async()=>{if(!lastResult)throw new Error('Generate the Permit Checklist before saving it to a Project.');const state=readState(),name=state.projectName.trim()||lastResult.typeLabel,likely=lastResult.permits.filter(item=>item.status==='likely').length;return{module:'permit-checklist',title:`${name} — Victoria Permit Checklist`,summary:`Guess only • ${likely} likely • ${lastResult.permits.length-likely} to confirm • written authority verification required`,recordRef,data:{state,result:lastResult,audit:{method:'Rule-based preliminary Victoria permit screening — best-effort guess only',rulesVersion:lastResult.version,generatedAt:lastResult.generatedAt,savedAt:new Date().toISOString(),generatedBy:window.ACAuth?.user?.()?.email||'authorised user',humanChanges:[]}}}};
  window.ACProjectSaved=({projectId,recordId})=>{recordRef={projectId,recordId};const state=readState();if(state.followUpDate){const project=window.ACProjects?.get(projectId),marker=`permit-checklist:${recordId}`;if(project&&!project.tasks?.some(task=>task.notes===marker))window.ACProjects.addTask(projectId,{title:`Confirm permits — ${state.projectName||lastResult.typeLabel}`,dueDate:state.followUpDate,priority:'High',notes:marker})}};
  function initialise(){let payload=null;try{payload=JSON.parse(localStorage.getItem(RESTORE_KEY)||'null')}catch(_){}if(payload){localStorage.removeItem(RESTORE_KEY);writeState(payload.state||{});recordRef=payload.projectId&&payload.recordId?{projectId:payload.projectId,recordId:payload.recordId}:null;const result=payload.result||payload.state?.result;if(result){render(result,payload.state||{})}else if(payload.state?.projectType){render(assess(payload.state),payload.state)}$('restoreNote').classList.add('show');return}try{const draft=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(draft?.state){writeState(draft.state);if(draft.result)render(draft.result,draft.state)}}catch(_){}}
  window.ACPermitChecklist={assess};initialise();
})();
