(function(global){
  'use strict';
  const config=global.AC_PLATFORM_CONFIG||{},CACHE_KEY='ac_price_catalogue_cache_v1';let rows=[],readyResolve;const ready=new Promise(resolve=>readyResolve=resolve);
  function defaults(){return(global.AC_CATALOGUE_DEFAULTS||[]).map(item=>({...item}))}
  function cacheKey(){return`${CACHE_KEY}:${global.ACAuth?.profile()?.organisation_id||'local'}`}
  function readCache(){try{return JSON.parse(localStorage.getItem(cacheKey())||'[]')}catch(_){return[]}}
  function writeCache(value){localStorage.setItem(cacheKey(),JSON.stringify(value))}
  function merged(){const map=new Map(defaults().map(item=>[item.item_key,item]));readCache().forEach(item=>map.set(item.item_key,{...(map.get(item.item_key)||{}),...item}));rows=[...map.values()].sort((a,b)=>String(a.trade).localeCompare(String(b.trade))||Number(a.sort_order)-Number(b.sort_order));return rows}
  function tradeFromPath(){const match=location.pathname.match(/\/(electrical|plumbing|cladding)\//);return match?.[1]||''}
  function list(trade){const source=rows.length?rows:merged();return source.filter(item=>!trade||item.trade===trade).sort((a,b)=>Number(a.sort_order)-Number(b.sort_order))}
  function effectiveRate(trade,index,fallback=0){return Number(list(trade).find(item=>Number(item.sort_order)===Number(index))?.builder_rate??fallback)}
  function applyCalculator(){const trade=tradeFromPath();if(!trade)return;const catalogue=list(trade),items=[...document.querySelectorAll('.item[data-rate]')];items.forEach((item,index)=>{const row=catalogue.find(candidate=>Number(candidate.sort_order)===index);if(!row)return;item.dataset.catalogueKey=row.item_key;item.setAttribute('data-rate',String(row.builder_rate));const rate=item.querySelector('.rate');if(rate)rate.textContent=Number(row.builder_rate).toLocaleString('en-AU',{style:'currency',currency:'AUD'})+' ex GST'});const api={electrical:global.ACQuoteCalculator,plumbing:global.ACPlumbingQuote,cladding:global.ACCladdingQuote}[trade];if(api?.calculateTotals)api.calculateTotals();else document.querySelector('.qtyInput')?.dispatchEvent(new Event('input',{bubbles:true}))}
  function applyToCatalogues(catalogues){Object.keys(catalogues||{}).forEach(trade=>{const target=catalogues[trade]?.items;if(!Array.isArray(target))return;list(trade).forEach(item=>{if(target[item.sort_order]){target[item.sort_order][0]=item.name||target[item.sort_order][0];target[item.sort_order][1]=Number(item.builder_rate)}})});return catalogues}
  async function context(){await global.ACAuth?.ready;const profile=global.ACAuth?.profile();if(!global.ACAuth?.isSignedIn()||!profile?.organisation_id)return null;return{profile,headers:{apikey:config.publishableKey,'Content-Type':'application/json',...(await global.ACAuth.headers())}}}
  async function loadCloud(){const ctx=await context();if(!ctx||!config.catalogueCloudEnabled)return merged();try{const response=await fetch(`${String(config.supabaseUrl).replace(/\/$/,'')}/rest/v1/price_catalogue?organisation_id=eq.${encodeURIComponent(ctx.profile.organisation_id)}&select=item_key,trade,sort_order,item_name,unit,builder_rate,margin_percent,active,source,updated_at&order=trade,sort_order`,{headers:ctx.headers});if(!response.ok)throw new Error(`Catalogue ${response.status}`);const cloud=(await response.json()).map(item=>({...item,name:item.item_name,customer_margin:Number(item.margin_percent)}));if(cloud.length){const map=new Map(readCache().map(item=>[item.item_key,item]));cloud.forEach(item=>map.set(item.item_key,item));writeCache([...map.values()])}merged();applyCalculator();global.dispatchEvent(new CustomEvent('ac-catalogue-changed',{detail:{rows:list()}}));return list()}catch(error){console.warn('AC catalogue cloud unavailable:',error.message);return merged()}}
  async function save(item){const next={...item,builder_rate:Number(item.builder_rate),customer_margin:Number(item.customer_margin||20),active:item.active!==false,updated_at:new Date().toISOString()},ctx=await context();if(ctx&&config.catalogueCloudEnabled){const payload={organisation_id:ctx.profile.organisation_id,item_key:next.item_key,trade:next.trade,sort_order:Number(next.sort_order),item_name:next.name,unit:next.unit||'each',builder_rate:next.builder_rate,margin_percent:next.customer_margin,active:next.active,source:next.source||'Office catalogue',updated_by:global.ACAuth.user()?.id||null};const response=await fetch(`${String(config.supabaseUrl).replace(/\/$/,'')}/rest/v1/price_catalogue?on_conflict=organisation_id,item_key`,{method:'POST',headers:{...ctx.headers,Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(payload)});if(!response.ok)throw new Error(`Catalogue save failed (${response.status}).`)}const map=new Map(readCache().map(row=>[row.item_key,row]));map.set(next.item_key,next);writeCache([...map.values()]);merged();applyCalculator();global.dispatchEvent(new CustomEvent('ac-catalogue-changed',{detail:{rows:list()}}));return next}
  async function init(){merged();applyCalculator();await loadCloud();readyResolve(list())}
  global.ACPriceCatalogue={ready,list,effectiveRate,applyCalculator,applyToCatalogues,loadCloud,save,cacheKey};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})(window);
