(function(){
  'use strict';const $=id=>document.getElementById(id);let draft=[],editable=false;
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function toast(text){const el=document.createElement('div');el.className='toast';el.textContent=text;document.body.appendChild(el);setTimeout(()=>el.remove(),2200)}
  function render(){const q=$('search').value.toLowerCase().trim(),trade=$('trade').value,rows=draft.filter(item=>(!trade||item.trade===trade)&&(!q||item.name.toLowerCase().includes(q)));$('rows').innerHTML=rows.length?rows.map(item=>`<div class="row" data-key="${esc(item.item_key)}"><span class="trade">${esc(item.trade)}</span><input data-field="name" value="${esc(item.name)}" ${editable?'':'readonly'}><input data-field="unit" value="${esc(item.unit||'each')}" ${editable?'':'readonly'}><input data-field="builder_rate" type="number" min="0" step="0.01" value="${Number(item.builder_rate)}" ${editable?'':'readonly'}><input data-field="customer_margin" type="number" min="0" step="1" value="${Number(item.customer_margin||20)}" ${editable?'':'readonly'}><button type="button" data-save ${editable?'':'disabled'}>${editable?'Save':'View'}</button></div>`).join(''):'<div class="empty">No catalogue items match this filter.</div>';if(!editable)return;document.querySelectorAll('.row').forEach(row=>{row.querySelectorAll('input').forEach(input=>input.addEventListener('input',()=>row.querySelector('[data-save]').classList.add('changed')));row.querySelector('[data-save]').addEventListener('click',()=>saveRow(row))})}
  async function saveRow(row){if(!editable)return;const item=draft.find(value=>value.item_key===row.dataset.key);row.querySelectorAll('[data-field]').forEach(input=>item[input.dataset.field]=input.type==='number'?Number(input.value):input.value.trim());const button=row.querySelector('[data-save]');button.disabled=true;button.textContent='Saving…';try{await ACPriceCatalogue.save(item);button.classList.remove('changed');button.textContent='Saved';toast('Catalogue rate saved')}catch(error){alert(error.message);button.textContent='Save'}finally{button.disabled=false}}
  $('search').addEventListener('input',render);$('trade').addEventListener('change',render);$('addBtn').addEventListener('click',()=>{if(!editable)return;const trade=$('trade').value||'electrical',order=Math.max(-1,...draft.filter(item=>item.trade===trade).map(item=>Number(item.sort_order)))+1,item={item_key:`${trade}:custom_${Date.now().toString(36)}`,trade,sort_order:order,name:'New catalogue item',unit:'each',builder_rate:0,customer_margin:20,active:true};draft.push(item);render();document.querySelector(`[data-key="${item.item_key}"] input`)?.focus()});
  async function init(){
    await ACAuth.ready;
    if(!ACAuth.isSignedIn()||!ACAuth.hasAccess()){$('lock').classList.add('show');$('status').textContent=ACAuth.isSignedIn()?'Catalogue locked — this account does not have active team access.':'Internal catalogue locked — sign in required.';return}
    await ACPriceCatalogue.ready;
    const security=ACPriceCatalogue.security();
    if(!security.verified){$('lock').classList.add('show');$('lock').querySelector('h2').textContent='Secure catalogue check failed';$('lock').querySelector('p').textContent=security.error||'The server did not authorise this catalogue request. Run the included security migration and try again.';$('status').textContent='Server authorization was not verified. No price catalogue has been displayed.';return}
    editable=security.can_edit===true&&ACAuth.can('owner','estimator');$('workspace').hidden=false;$('addBtn').disabled=!editable;$('status').textContent=editable?'Server authorization verified • RLS protected • Changes are versioned with your account.':'Server authorization verified • Read-only Site Supervisor access.';draft=ACPriceCatalogue.list().map(item=>({...item}));render()
  }
  init();
})();
