-- Alert Construction privacy-safe first-party usage analytics.
-- Run after the foundation, security hardening and optional Team Code migrations.
-- Events intentionally exclude project names, addresses, uploaded files, notes,
-- estimate values, quote contents, search terms and other free text.

create table if not exists public.ac_usage_events (
  id bigint generated by default as identity primary key,
  organisation_id uuid not null references public.organisations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_name text not null check (event_name in ('tool_opened','estimate_completed','record_saved')),
  tool text not null check (tool ~ '^[a-z0-9-]{1,60}$'),
  path text not null check (char_length(path) between 1 and 180),
  occurred_at timestamptz not null default now()
);

create index if not exists ac_usage_events_org_time_idx
on public.ac_usage_events(organisation_id, occurred_at desc);

create index if not exists ac_usage_events_org_tool_idx
on public.ac_usage_events(organisation_id, tool, occurred_at desc);

alter table public.ac_usage_events enable row level security;

drop policy if exists usage_owner_select on public.ac_usage_events;
create policy usage_owner_select on public.ac_usage_events for select to authenticated
using (organisation_id = public.current_organisation_id() and public.current_ac_role() = 'owner');

revoke all on public.ac_usage_events from anon, authenticated;
grant select on public.ac_usage_events to authenticated;

create or replace function public.log_ac_usage(
  p_event_name text,
  p_tool text,
  p_path text
)
returns void language plpgsql security definer set search_path = public
as $$
declare
  org_id uuid := public.current_organisation_id();
  clean_tool text := lower(trim(coalesce(p_tool,'')));
  clean_path text := left(split_part(split_part(coalesce(p_path,'/'),'?',1),'#',1),180);
begin
  if auth.uid() is null or org_id is null then raise exception 'Active signed-in workspace required'; end if;
  if p_event_name not in ('tool_opened','estimate_completed','record_saved') then raise exception 'Unsupported usage event'; end if;
  if clean_tool !~ '^[a-z0-9-]{1,60}$' then raise exception 'Invalid tool name'; end if;
  if clean_path = '' then clean_path := '/'; end if;

  -- Apply retention during normal writes so detailed events do not accumulate forever.
  delete from public.ac_usage_events
  where organisation_id = org_id and occurred_at < now() - interval '180 days';

  insert into public.ac_usage_events(organisation_id,user_id,event_name,tool,path)
  values (org_id,auth.uid(),p_event_name,clean_tool,clean_path);
end;
$$;

create or replace function public.ac_usage_summary(p_days integer default 30)
returns table(tool text, uses bigint, unique_users bigint, last_used timestamptz)
language plpgsql stable security definer set search_path = public
as $$
declare
  org_id uuid := public.current_organisation_id();
  days_to_show integer := greatest(1,least(coalesce(p_days,30),180));
begin
  if auth.uid() is null or org_id is null then raise exception 'Active signed-in workspace required'; end if;
  if public.current_ac_role() <> 'owner' then raise exception 'Only an Owner can view usage analytics'; end if;
  return query
    select e.tool,count(*)::bigint,count(distinct e.user_id)::bigint,max(e.occurred_at)
    from public.ac_usage_events e
    where e.organisation_id = org_id
      and e.event_name = 'tool_opened'
      and e.occurred_at >= now() - make_interval(days => days_to_show)
    group by e.tool
    order by count(*) desc,max(e.occurred_at) desc;
end;
$$;

revoke execute on function public.log_ac_usage(text,text,text) from public, anon;
revoke execute on function public.ac_usage_summary(integer) from public, anon;
grant execute on function public.log_ac_usage(text,text,text) to authenticated;
grant execute on function public.ac_usage_summary(integer) to authenticated;

notify pgrst, 'reload schema';
